vich_uploader:
    db_driver: orm

    mappings:
      users_profile:
            uri_prefix: /users_profile
            upload_destination: '%kernel.project_dir%/public/users_profile'
      images:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images'
